apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kvapp
  name: kvapp
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: kvapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kvapp
    spec:
      containers:
        - image: anishjha025/kvapp:v0.0
          name: kvapp
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
