apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: storage
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: storage
    spec:
      containers:
        - image: anishjha025/kvstorage:v0.0
          name: storage
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
